version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: quiz-mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quiz
      MYSQL_USER: quizUser
      MYSQL_PASSWORD: quiz
    ports:
      - "3316:3316"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: